services:
  comfyui:
    image: behealy/my_comfy_pod:0.0.7-bakedin-cpu
    ports:
      - "3001:3001" # ComfyUI
      - "8889:8889"   # Jupyter Lab
      - "4040:4040"   # Filebrowser
      - "8001:8001"   # VS code server
    environment:
      - JUPYTER_PASSWORD=joopies
    volumes:
      - ./workspace:/workspace
    profiles:
      - cpu

